#!/usr/bin/env bash

PERIOD=5

function toggle() {
    function setgov() {
        local nbcpus
        read -r nbcpus < <(cpufreq-info | grep -c 'CPU [[:digit:]]:')
        for i in $(seq 0 $((nbcpus - 1))); do
            sudo cpufreq-set -c "$i" -g "$1"
        done
    }
    local governor
    read -r governor < <(cpufreq-info | sed -rn '/may decide/s/.*"(.*)".*/\1/p' | head -1)
    case "$governor" in
        powersave) setgov performance ;;
        performance) setgov powersave ;;
    esac
}

function run() {
    menu process
}

function text() {
    local text availram totalram

    read -r availram < <(free | awk '/^Mem:/ {print $7}')
    read -r totalram < <(free | awk '/^Mem:/ {print $2}')
    read -r text < <(bc <<< "$availram * 100 / $totalram")
    printf "%s" "$text"
}

function icon() {
    local cpupath=/sys/devices/system/cpu
    local -a governors
    readarray -t governors < <(cat $cpupath/cpu*/cpufreq/scaling_governor | uniq)

    local powersave=󰌲
    local performance=󰍛
    local ambiguous=󰌨
    local icon="$ambiguous"

    (( ${#governors[@]} <= 0 || ${#governors[@]} >= 2)) && ICON=

    (( ${#governors[@]} <= 0 || ${#governors[@]} >= 2)) ||
        case "${governors[0]}" in
            powersave) icon="$powersave";;
            performance) icon="$performance";;
        esac


    printf "%s" "$icon"
}
